from analysis_tools import Feature
from plotting_tools import Label

features = [

    ###########
    # L1 JETS #
    ###########
    Feature("jet_pt", "L1Jet_pt",
        binning=(60, 0, 300),
        x_title=Label("L1Jet_pt"),
    ),
    Feature("jet_eta", "L1Jet_eta",
        binning=(100, -5, 5),
        x_title=Label("L1Jet_eta"),
    ),
    Feature("jet_phi", "L1Jet_phi",
        binning=(100, -3.5, 3.5),
        x_title=Label("L1Jet_phi"),
    ),
    Feature("mjj", "mjj",
        binning=(550, 150, 700),
        x_title=Label("mjj"),
    ),
    Feature("mjj_scale", "mjj_scale",
        binning=(550, 150, 700),
        x_title=Label("mjj scaled to data"),
    ),
    Feature("deta", "deta",
        binning=(100, 0.0, 6.0),
        x_title=Label("deta"),
        selection=("(mjj > 200) && (mjj < 700)"),
    ),
    Feature("dphi", "dphi",
        binning=(34, 1.047, 3.2),
        x_title=Label("dphi"),
        selection=("(mjj > 200) && (mjj < 700)"),
    ),
    Feature("pt", "pt",
        binning=(200, 0, 1000),
        x_title=Label("Dijet p_{T} [GeV]"),
        selection=("(mjj > 200) && (mjj < 700)"),
    ),
    Feature("lead_pt", "L1Jet_pt[0]",
        binning=(200, 0, 1000),
        x_title=Label("Leading L1Jet p_{T} [GeV]"),
        selection=("(mjj > 200) && (mjj < 700)"),
    ),
    Feature("sublead_pt", "L1Jet_pt[1]",
        binning=(200, 0, 1000),
        x_title=Label("Subleading L1Jet p_{T} [GeV]"),
        selection=("(mjj > 200) && (mjj < 700)"),
    ),
    Feature("lead_eta", "L1Jet_eta[0]",
        binning=(64, -2.5, 2.5),
        x_title=Label("Leading L1Jet #eta"),
        selection=("(mjj > 200) && (mjj < 700)"),
    ),
    Feature("sublead_eta", "L1Jet_eta[1]",
        binning=(64, -2.5, 2.5),
        x_title=Label("Subleading L1Jet #eta"),
        selection=("(mjj > 200) && (mjj < 700)"),
    ),
    Feature("lead_phi", "L1Jet_phi[0]",
        binning=(64, -3.2, 3.2),
        x_title=Label("Leading L1Jet #phi"),
        selection=("(mjj > 200) && (mjj < 700)"),
    ),
    Feature("sublead_phi", "L1Jet_phi[1]",
        binning=(64, -3.2, 3.2),
        x_title=Label("Subleading L1Jet #phi"),
        selection=("(mjj > 200) && (mjj < 700)"),
    ),
    Feature("mjj_fine", "mjj",
        binning=(4400, 150, 700),
        x_title=Label("mjj"),
    ),
    Feature("mjj_full", "mjj",
        binning=(1000, 0, 1000),
        x_title=Label("mjj"),
    ),
    # Quantities after applying JECs
    Feature("jet_pt_order", "L1Jet_pt_order",
        binning=(10, 0, 10),
        x_title=Label("Jet index (pT sorted)")        
    ),
    Feature("jet_pt_scale_corr_order", "L1Jet_pt_scale_corr_order",
        binning=(10, 0, 10),
        x_title=Label("Jet index after corr. (pT sorted)")        
    ),
    Feature("jet_pt_scale_corr_order_shift", "L1Jet_pt_scale_corr_order_shift",
        binning=(20, -10, 10),
        x_title=Label("Jet index shift after correction (pT sorted)")        
    ),
    # Note the order of the jets might change after correction so eta and phi also need to be redefined
    Feature("jet_pt_scale_corr", "L1Jet_pt_scale_corr",
        binning=(200, 0, 1000),
        x_title=Label("Leading L1Jet p_{T} (pT corr.) [GeV]"),
        selection=("(mjj_scale_corr > 200) && (mjj_scale_corr < 700)"),
    ),
    Feature("lead_pt_scale_corr", "L1Jet_pt_scale_corr[0]",
        binning=(200, 0, 1000),
        x_title=Label("Leading L1Jet p_{T} (pT corr.) [GeV]"),
        selection=("(mjj_scale_corr > 200) && (mjj_scale_corr < 700)"),
    ),
    Feature("sublead_pt_scale_corr", "L1Jet_pt_scale_corr[1]",
        binning=(200, 0, 1000),
        x_title=Label("Subleading L1Jet p_{T} (pT corr.) [GeV]"),
        selection=("(mjj_scale_corr > 200) && (mjj_scale_corr < 700)"),
    ),
    Feature("lead_eta_scale_corr", "L1Jet_eta_scale_corr[0]",
        binning=(64, -2.5, 2.5),
        x_title=Label("Leading L1Jet #eta (pT corr.)"),
        selection=("(mjj_scale_corr > 200) && (mjj_scale_corr < 700)"),
    ),
    Feature("sublead_eta_scale_corr", "L1Jet_eta_scale_corr[1]",
        binning=(64, -2.5, 2.5),
        x_title=Label("Subleading L1Jet #eta (pT corr.)"),
        selection=("(mjj_scale_corr > 200) && (mjj_scale_corr < 700)"),
    ),
    Feature("lead_phi_scale_corr", "L1Jet_phi_scale_corr[0]",
        binning=(64, -3.2, 3.2),
        x_title=Label("Leading L1Jet #phi (pT corr.)"),
        selection=("(mjj_scale_corr > 200) && (mjj_scale_corr < 700)"),
    ),
    Feature("sublead_phi_scale_corr", "L1Jet_phi_scale_corr[1]",
        binning=(64, -3.2, 3.2),
        x_title=Label("Subleading L1Jet #phi (pT corr.)"),
        selection=("(mjj_scale_corr > 200) && (mjj_scale_corr < 700)"),
    ),
    Feature("deta_scale_corr", "deta_scale_corr",
        binning=(100, 0.0, 6.0),
        x_title=Label("deta (pT corr.)"),
        selection=("(mjj_scale_corr > 200) && (mjj_scale_corr < 700)"),
    ),
    Feature("dphi_scale_corr", "dphi_scale_corr",
        binning=(34, 1.047, 3.2),
        x_title=Label("dphi (pT corr.)"),
        selection=("(mjj_scale_corr > 200) && (mjj_scale_corr < 700)"),
    ),
    Feature("mjj_full_scale_corr", "mjj_scale_corr",
        binning=(1000, 0, 1000),
        x_title=Label("mjj (pT corr.)"),
    ),
    # Jet quality
    Feature("jet_egiso", "L1Jet_EGIso",
        binning=(200, 0, 2),
        x_title=Label("Relative EGamma isolation"),  
        selection=("(mjj > 200) && (mjj < 700)"),      
    ),
    Feature("jet_muiso", "L1Jet_MuIso",
        binning=(200, 0, 2),
        x_title=Label("Relative Muon isolation"),   
        selection=("(mjj > 200) && (mjj < 700)"),     
    ),
    Feature("jet_ismatchedtoreco", "L1Jet_isMatchedToReco",
        binning=(2, 0, 2),
        x_title=Label("Is matched to clean reco jet"),   
        selection=("(mjj > 200) && (mjj < 700)"),
    ),
    Feature("jet_egiso_ismatchedtoreco", "L1Jet_EGIso[L1Jet_isMatchedToReco==true]",
        binning=(200, 0, 2),
        x_title=Label("Relative EGamma isolation (matched to reco)"),  
        selection=("(mjj > 200) && (mjj < 700)"),      
    ),
    Feature("jet_muiso_ismatchedtoreco", "L1Jet_MuIso[L1Jet_isMatchedToReco==true]",
        binning=(200, 0, 2),
        x_title=Label("Relative Muon isolation (matched to reco)"),   
        selection=("(mjj > 200) && (mjj < 700)"),     
    ),
    Feature("jet_egiso_isnotmatchedtoreco", "L1Jet_EGIso[!L1Jet_isMatchedToReco]",
        binning=(200, 0, 2),
        x_title=Label("Relative EGamma isolation (matched to reco)"),  
        selection=("(mjj > 200) && (mjj < 700)"),      
    ),
    Feature("jet_muiso_isnotmatchedtoreco", "L1Jet_MuIso[!L1Jet_isMatchedToReco]",
        binning=(200, 0, 2),
        x_title=Label("Relative Muon isolation (matched to reco)"),   
        selection=("(mjj > 200) && (mjj < 700)"),     
    ),
    # Gen features
    Feature("gen_pthat", "GenPtHat_hardPtHat",
        binning=(100000, 10, 1010),
        x_title=Label("Gen pT hat [GeV]")        
    ),
    Feature("pileup_pthats", "PileupPtHat_puPtHats",
        binning=(100, 0, 300),
        x_title=Label("Pileup pT hats [GeV]")        
    ),
    Feature("event_pthats", "EventPtHats",
        binning=(100, 0, 300),
        x_title=Label("Event pT hats [GeV]")        
    ),
    Feature("ntrueint", "Pileup_nTrueInt",
        binning=(100, 0, 100),
        x_title=Label("nTrueInt")
    ),
    Feature("nl1jet", "nL1Jet",
        binning=(12, 0, 12),
        x_title=Label("nL1Jet")
    ),
]