# Tag and probe version of systematics 

from analysis_tools import Feature
from plotting_tools import Label

# Encoding function to convert -3.0 to "neg3p0" and 3.0 to "pos3p0"
def convert_eta_float_to_str(eta):
    if eta < 0:
        return "neg" + str(abs(eta)).replace(".", "p")
    else:
        return "pos" + str(eta).replace(".", "p")

# Dijet features
dijet_features = [
    Feature("dphi", "L1Dijet_dphi",
        binning=(70, -3.5, 3.5),
        x_title=("L1Dijet_dphi")       
    ),
    Feature("absdphi", "abs(L1Dijet_dphi)",
        binning=(35, 0, 3.5),
        x_title=("|L1Dijet_dphi|")       
    ),
    Feature("passSelection", "passSelection",
        binning=(2, 0, 2),
        x_title=("passSelection"),
    ),
    Feature("averagePt", "0.5*(L1Jet_pt[0] + L1Jet_pt[1])",
        binning=(100, 0, 100),
        x_title=("(pT,1 + pT,2)*0.5"),
    ),
    Feature("balancePt", "(L1Jet_pt[2])/(0.5*(L1Jet_pt[0] + L1Jet_pt[1]))",
        binning=(50, 0, 1),
        x_title=("pT,3/((pT,1 + pT,2)*0.5)"),
    ),
    Feature("thirdjet_pt", "L1Jet_pt[2]",
        binning=(100, 0, 100),
        x_title=("Third jet pT"),    
    ),
    Feature("thirdjet_pt_pass", "L1Jet_pt[2]",
        binning=(100, 0, 100),
        selection=("(passSelection == true)"),
        x_title=("Third jet pT (pass selection)"),    
    ),
    Feature("thirdjet_pt_fail", "L1Jet_pt[2]",
        binning=(100, 0, 100),
        selection=("(passSelection == false)"),
        x_title=("Third jet pT (fail selection)"),    
    ),
    Feature("thirdjet_eta", "L1Jet_eta[2]",
        binning=(100, -5.0, 5.0),
        x_title=("Third jet eta"),    
    ),
    Feature("thirdjet_eta_pass", "L1Jet_eta[2]",
        binning=(100, -5.0, 5.0),
        selection=("(passSelection == true)"),
        x_title=("Third jet eta (pass selection)"),    
    ),
    Feature("thirdjet_eta_fail", "L1Jet_eta[2]",
        binning=(100, -5.0, 5.0),
        selection=("(passSelection == false)"),
        x_title=("Third jet eta (fail selection)"),    
    ),
    Feature("thirdjet_phi", "L1Jet_phi[2]",
        binning=(62, -3.2, 3.2),
        x_title=("Third jet phi"),    
    ),
    Feature("thirdjet_phi_pass", "L1Jet_phi[2]",
        binning=(62, -3.2, 3.2),
        selection=("(passSelection == true)"),
        x_title=("Third jet phi (pass selection)"),    
    ),
    Feature("thirdjet_phi_fail", "L1Jet_phi[2]",
        binning=(62, -3.2, 3.2),
        selection=("(passSelection == false)"),
        x_title=("Third jet phi (fail selection)"),    
    ),
    Feature("nL1Jet", "nL1Jet",
        binning=(10, 0, 10),
        x_title=("nL1Jet"),
    ),
    Feature("nL1Jet_pass", "nL1Jet",
        binning=(10, 0, 10),
        selection=("(passSelection == true)"),
        x_title=("nL1Jet (pass selection)"),
    ),
    Feature("nL1Jet_fail", "nL1Jet",
        binning=(10, 0, 10),
        selection=("(passSelection == false)"),
        x_title=("nL1Jet (fail selection)"),
    ),
]
# Response features
response_features = [
    Feature("tag_l1pt", "tag_l1pt",
        binning=(500, 0, 500),
        x_title=Label("Tag L1 pT"),
    ),
    Feature("tag_recopt", "tag_recopt",
        binning=(500, 0, 500),
        x_title=Label("Tag Reco pT"),
    ),
    Feature("tag_l1eta", "tag_l1eta",
        binning=(100, -5.0, 5.0),
        x_title=Label("Tag L1 eta"),
    ),
    Feature("probe_l1pt", "probe_l1pt",
        binning=(1000, 0, 1000),
        x_title=Label("Probe L1 pT"),
    ),
    Feature("probe_recopt", "probe_recopt",
        binning=(1000, 0, 1000),
        x_title=Label("Probe Reco pT"),
    ),
    Feature("probe_l1eta", "probe_l1eta",
        binning=(100, -5.0, 5.0),
        x_title=Label("Probe L1 eta"),
    ),
    Feature("probe_l1pt_over_tag_recopt", "probe_l1pt_over_tag_recopt",
        binning=(100, 0.0, 3.0),
        x_title=Label("pT(L1, Probe)/pT(Reco, Tag)"),
    ),
    Feature("probe_recopt_over_tag_recopt", "probe_recopt_over_tag_recopt",
        binning=(100, 0.0, 3.0),
        x_title=Label("pT(Reco, Probe)/pT(Reco, Tag)"),
    ),
    Feature("probe_l1pt_over_probe_recopt", "probe_l1pt_over_probe_recopt",
        binning=(100, 0.0, 3.0),
        x_title=Label("pT(L1, Probe)/pT(Reco, Probe)"),
    ),
]

eta_edges = [-2.5, -2.0, -1.3, -0.5, 0.0, 0.5, 1.3, 2.0, 2.5]

for i_bin in range(len(eta_edges) - 1):
    eta_low = eta_edges[i_bin]
    eta_high = eta_edges[i_bin + 1]
    eta_cut = f"(probe_l1eta >= {eta_low}) && (probe_l1eta < {eta_high})"
    eta_cut_string = f"{convert_eta_float_to_str(eta_low)}to{convert_eta_float_to_str(eta_high)}"

    response_features_i = [
        Feature(f"tag_l1pt_{eta_cut_string}", f"tag_l1pt[{eta_cut}]",
            binning=(500, 0, 500),
            x_title=Label("Tag L1 pT"),
        ),
        Feature(f"tag_recopt_{eta_cut_string}", f"tag_recopt[{eta_cut}]",
            binning=(500, 0, 500),
            x_title=Label("Tag Reco pT"),
        ),
        Feature(f"tag_l1eta_{eta_cut_string}", f"tag_l1eta[{eta_cut}]",
            binning=(100, -5.0, 5.0),
            x_title=Label("Tag L1 eta"),
        ),
        Feature(f"probe_l1pt_{eta_cut_string}", f"probe_l1pt[{eta_cut}]",
            binning=(1000, 0, 1000),
            x_title=Label("Probe L1 pT"),
        ),
        Feature(f"probe_recopt_{eta_cut_string}", f"probe_recopt[{eta_cut}]",
            binning=(1000, 0, 1000),
            x_title=Label("Probe Reco pT"),
        ),
        Feature(f"probe_l1eta_{eta_cut_string}", f"probe_l1eta[{eta_cut}]",
            binning=(100, -5.0, 5.0),
            x_title=Label("Probe L1 eta"),
        ),
        Feature(f"probe_l1pt_over_tag_recopt_{eta_cut_string}", f"probe_l1pt_over_tag_recopt[{eta_cut}]",
            binning=(100, 0.0, 3.0),
            x_title=Label("pT(L1, Probe)/pT(Reco, Tag)"),
        ),
        Feature(f"probe_recopt_over_tag_recopt_{eta_cut_string}", f"probe_recopt_over_tag_recopt[{eta_cut}]",
            binning=(100, 0.0, 3.0),
            x_title=Label("pT(Reco, Probe)/pT(Reco, Tag)"),
        ),
        Feature(f"probe_l1pt_over_probe_recopt_{eta_cut_string}", f"probe_l1pt_over_probe_recopt[{eta_cut}]",
            binning=(100, 0.0, 3.0),
            x_title=Label("pT(L1, Probe)/pT(Reco, Probe)"),
        ),
    ]

    response_features += response_features_i

response_features_lastbin = [
    Feature(f"tag_l1pt_neg2p5topos2p5", f"tag_l1pt[(probe_l1eta >= -2.5) && (probe_l1eta < 2.5)]",
        binning=(500, 0, 500),
        x_title=Label("Tag L1 pT"),
    ),
    Feature(f"tag_recopt_neg2p5topos2p5", f"tag_recopt[(probe_l1eta >= -2.5) && (probe_l1eta < 2.5)]",
        binning=(500, 0, 500),
        x_title=Label("Tag Reco pT"),
    ),
    Feature(f"tag_l1eta_neg2p5topos2p5", f"tag_l1eta[(probe_l1eta >= -2.5) && (probe_l1eta < 2.5)]",
        binning=(100, -5.0, 5.0),
        x_title=Label("Tag L1 eta"),
    ),
    Feature(f"probe_l1pt_neg2p5topos2p5", f"probe_l1pt[(probe_l1eta >= -2.5) && (probe_l1eta < 2.5)]",
        binning=(1000, 0, 1000),
        x_title=Label("Probe L1 pT"),
    ),
    Feature(f"probe_recopt_neg2p5topos2p5", f"probe_recopt[(probe_l1eta >= -2.5) && (probe_l1eta < 2.5)]",
        binning=(1000, 0, 1000),
        x_title=Label("Probe Reco pT"),
    ),
    Feature(f"probe_l1eta_neg2p5topos2p5", f"probe_l1eta[(probe_l1eta >= -2.5) && (probe_l1eta < 2.5)]",
        binning=(100, -5.0, 5.0),
        x_title=Label("Probe L1 eta"),
    ),
    Feature(f"probe_l1pt_over_tag_recopt_neg2p5topos2p5", f"probe_l1pt_over_tag_recopt[(probe_l1eta >= -2.5) && (probe_l1eta < 2.5)]",
        binning=(100, 0.0, 3.0),
        x_title=Label("pT(L1, Probe)/pT(Reco, Tag)"),
    ),
    Feature(f"probe_recopt_over_tag_recopt_neg2p5topos2p5", f"probe_recopt_over_tag_recopt[(probe_l1eta >= -2.5) && (probe_l1eta < 2.5)]",
        binning=(100, 0.0, 3.0),
        x_title=Label("pT(Reco, Probe)/pT(Reco, Tag)"),
    ),
    Feature(f"probe_l1pt_over_probe_recopt_neg2p5topos2p5", f"probe_l1pt_over_probe_recopt[(probe_l1eta >= -2.5) && (probe_l1eta < 2.5)]",
        binning=(100, 0.0, 3.0),
        x_title=Label("pT(L1, Probe)/pT(Reco, Probe)"),
    ),
]

features = dijet_features + response_features + response_features_lastbin