# Features are defined per category (outsources analysis selections to PrePlot)
from analysis_tools import Feature
from plotting_tools import Label

features = [

    ###########
    # L1 JETS #
    ###########
    # Uncorrected quantities
    Feature("mjj", "mjj",
        binning=(1000, 0, 1000),
        x_title=Label("mjj"),
    ),
    Feature("deta", "deta",
        binning=(60, 0.0, 6.0),
        x_title=Label("deta"),
        selection=("(mjj > 150) && (mjj < 700)"),
    ),
    Feature("deta_full", "deta",
        binning=(60, 0.0, 6.0),
        x_title=Label("deta"),
    ),
    Feature("dphi", "dphi",
        binning=(22, 1.0, 3.2),
        x_title=Label("dphi"),
        selection=("(mjj > 150) && (mjj < 700)"),
    ),
    Feature("dphi_full", "dphi",
        binning=(22, 1.0, 3.2),
        x_title=Label("dphi"),
    ),
    Feature("pt", "pt",
        binning=(512, 0, 1024),
        x_title=Label("Dijet p_{T} [GeV]"),
        selection=("(mjj > 150) && (mjj < 700)"),
    ),
    Feature("pt_full", "pt",
        binning=(512, 0, 1024),
        x_title=Label("Dijet p_{T} [GeV]"),
    ),
    Feature("lead_pt", "L1Jet_pt[0]",
        binning=(512, 0, 1024),
        x_title=Label("Leading L1Jet p_{T} [GeV]"),
        selection=("(mjj > 150) && (mjj < 700)"),
    ),
    Feature("lead_pt_full", "L1Jet_pt[0]",
        binning=(512, 0, 1024),
        x_title=Label("Leading L1Jet p_{T} [GeV]"),
    ),
    Feature("sublead_pt", "L1Jet_pt[1]",
        binning=(512, 0, 1024),
        x_title=Label("Subleading L1Jet p_{T} [GeV]"),
        selection=("(mjj > 150) && (mjj < 700)"),
    ),
    Feature("sublead_pt_full", "L1Jet_pt[1]",
        binning=(512, 0, 1024),
        x_title=Label("Subleading L1Jet p_{T} [GeV]"),
    ),
    Feature("lead_eta", "L1Jet_eta[0]",
        binning=(52, -2.6, 2.6),
        x_title=Label("Leading L1Jet #eta"),
        selection=("(mjj > 150) && (mjj < 700)"),
    ),
    Feature("lead_eta_full", "L1Jet_eta[0]",
        binning=(52, -2.6, 2.6),
        x_title=Label("Leading L1Jet #eta"),
    ),
    Feature("sublead_eta", "L1Jet_eta[1]",
        binning=(52, -2.6, 2.6),
        x_title=Label("Subleading L1Jet #eta"),
        selection=("(mjj > 150) && (mjj < 700)"),
    ),
    Feature("sublead_eta_full", "L1Jet_eta[1]",
        binning=(52, -2.6, 2.6),
        x_title=Label("Subleading L1Jet #eta"),
    ),
    Feature("lead_phi", "L1Jet_phi[0]",
        binning=(64, -3.2, 3.2),
        x_title=Label("Leading L1Jet #phi"),
        selection=("(mjj > 150) && (mjj < 700)"),
    ),
    Feature("lead_phi_full", "L1Jet_phi[0]",
        binning=(64, -3.2, 3.2),
        x_title=Label("Leading L1Jet #phi"),
    ),
    Feature("sublead_phi", "L1Jet_phi[1]",
        binning=(64, -3.2, 3.2),
        x_title=Label("Subleading L1Jet #phi"),
        selection=("(mjj > 150) && (mjj < 700)"),
    ),
    Feature("sublead_phi_full", "L1Jet_phi[1]",
        binning=(64, -3.2, 3.2),
        x_title=Label("Subleading L1Jet #phi"),
    ),
    Feature("ntrueint", "Pileup_nTrueInt",
        binning=(100, 0, 100),
        x_title=Label("nTrueInt"),
    ),
    Feature("puWeight", "puWeight",
        binning=(50, 0, 5),
        x_title=Label("puWeight"),
        systematics=["pu"],
    ),
    #################################
    # Reco and gen quantities #
    #################################
    Feature("mjj_reco", "mjj_reco",
        binning=(1000, 0, 1000),
        x_title=Label("mjj_reco"),
    ),
    Feature("mjj_gen", "mjj_gen",
        binning=(1000, 0, 1000),
        x_title=Label("mjj_gen"),
    ),
    Feature("recoscale", "Take(L1Jet_recoScale, {0, 1})",
        binning=(50, 0, 3),
        x_title=Label("L1Jet/Reco pT"),
    ),
    Feature("genscale", "Take(L1Jet_genScale, {0, 1})",
        binning=(50, 0, 3),
        x_title=Label("L1Jet/Gen pT"),
    ),
    Feature("lead_recoscale", "L1Jet_recoScale[0]",
        binning=(50, 0, 3),
        x_title=Label("Leading L1Jet/Reco pT"),
    ),
    Feature("sublead_recoscale", "L1Jet_recoScale[1]",
        binning=(50, 0, 3),
        x_title=Label("Subleading L1Jet/Reco pT"),
    ),
    Feature("lead_recoscale_corr", "L1Jet_recoScaleCorr[0]",
        binning=(50, 0, 3),
        x_title=Label("Leading L1Jet/Reco pT"),
    ),
    Feature("sublead_recoscale_corr", "L1Jet_recoScaleCorr[1]",
        binning=(50, 0, 3),
        x_title=Label("Subleading L1Jet/Reco pT"),
    ),
    Feature("lead_genscale", "L1Jet_genScale[0]",
        binning=(50, 0, 3),
        x_title=Label("Leading L1Jet/Gen pT"),
    ),
    Feature("sublead_genscale", "L1Jet_genScale[1]",
        binning=(50, 0, 3),
        x_title=Label("Subleading L1Jet/Gen pT"),
    ),
    Feature("lead_genscale_corr", "L1Jet_genScaleCorr[0]",
        binning=(50, 0, 3),
        x_title=Label("Leading L1Jet/Gen pT"),
    ),
    Feature("sublead_genscale_corr", "L1Jet_genScaleCorr[1]",
        binning=(50, 0, 3),
        x_title=Label("Subleading L1Jet/Gen pT"),
    ),
]