qcd_reweight:
  name: QCDWeight
  path: L1DS.Modules.QCDWeightCalc
  parameters:
    year: self.config.year
    isMC: self.dataset.process.isMC

ntrueint_reweight:
  name: puWeightRDF
  path: modules.puWeight
  parameters:
    year: self.config.year
    isMC: self.dataset.process.isMC
    process: self.dataset.process.name

muonjet_skim:
  name: MuonJet
  path: modules.jet_pt_systematics_skim
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC