jet_pt_scale:
  name: JetPtScale
  path: modules.jet_pt_systematics_nano_v2
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC

jet_pt_reshuffle:
  name: JetPtReshuffleScale
  path: modules.jet_pt_systematics_nano_v2
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC

muonjet_skim:
  name: MuonJetScale
  path: modules.jet_pt_systematics_skim
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC