recojet_pt_scale:
  name: RecoJetPtScale
  path: modules.jec_application
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC

recojet_pt_resolution:
  name: RecoJetPtResolution
  path: modules.jec_application
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC

jetvetomap:
  name: JetVetoMap
  path: modules.jec_application
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC