recojet_pt_scale:
  name: RecoJetPtScale
  path: modules.jet_pt_systematics_new
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC

recojet_pt_resolution:
  name: RecoJetPtResolution
  path: modules.jet_pt_systematics_new
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC

jetvetomap:
  name: JetVetoMap
  path: modules.jet_pt_systematics_new
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC

dijet_tnp:
  name: DijetTagAndProbe
  path: modules.jet_pt_systematics_skim_new
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC
    triggerType: self.dataset.get_aux('triggerType')