jet_pt_scale_unity_mc:
  name: JetPtScaleMC
  path: modules.jet_pt_systematics_nano
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC

jet_pt_reshuffle:
  name: JetPtReshuffle
  path: modules.jet_pt_systematics_nano
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC

jet_pt_reshuffle_reorder:
  name: JetPtReshuffleReorder
  path: modules.jet_pt_systematics_nano
  parameters:
    runPeriod: self.dataset.runPeriod
    isMC: self.dataset.process.isMC