xs_weight:
  name: EventWeight
  path: modules.xsweight
  parameters:
    xs: self.dataset.xs
    nr_incl: self.dataset.get_aux('nr_incl', 1)

pileup_veto:
  name: PileupVetoNano
  path: modules.xsweight
  
qcd_reweight:
  name: QCDWeight
  path: L1DS.Modules.QCDWeightCalc
  parameters:
    year: self.config.year
    isMC: self.dataset.process.isMC

inclusive_dijet_selection:
  name: InclusiveDijetSelection
  path: modules.dijet_selection_2025
  parameters:
    year: self.config.year
  
l1_match_to_reco:
  name: L1MatchToReco
  path: modules.dijet_selection_2025
  parameters:
    year: self.config.year

inclusive_dijet_selection_reco:
  name: InclusiveDijetSelectionReco
  path: modules.dijet_selection_2025
  parameters:
    year: self.config.year